name: botapp
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.17.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_svg: ^0.22.0
  carousel_slider: ^4.0.0
  url_launcher: ^6.0.10
  flutter_launcher_icons: ^0.9.2
  flutter_media_metadata: ^0.1.1
  audioplayers: ^0.20.0
  battery_indicator: ^0.1.0
  battery_plus: ^1.1.1
  wakelock: ^0.5.6
  wakelock_web: ^0.4.0
  flutter_secure_storage: ^4.2.1
  get: ^4.3.8
  http: ^0.13.3
  file_picker: ^4.1.3
  flutter_phone_direct_caller: ^2.0.0
  just_audio: ^0.9.13
  just_audio_web: ^0.4.2
  audio_session: ^0.1.6+1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/AhBotIcon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/cutefaces/
    - assets/icons/
    - assets/backgroundbanner.png
    - assets/dark-second-hand.png
    - assets/fadedsun.png
    - assets/light-second-hand.png
    - assets/loginbackground.png
    - assets/sun.png
    - assets/uploadfinished.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
        - asset: fonts/Montserrat-Italic.ttf
          style: italic
        - asset: fonts/Montserrat-Thin.ttf
          weight: 100
        - asset: fonts/Montserrat-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: fonts/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: fonts/Montserrat-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: fonts/Montserrat-Light.ttf
          weight: 300
        - asset: fonts/Montserrat-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: fonts/Montserrat-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: fonts/Montserrat-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: fonts/Montserrat-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: fonts/Montserrat-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: fonts/Montserrat-Black.ttf
          weight: 900
        - asset: fonts/Montserrat-BlackItalic.ttf
          weight: 900
          style: italic
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
